/* Generated by cbindgen */

#ifndef pgp_ffi_h
#define pgp_ffi_h

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Certificate Certificate;

typedef struct Key Key;

typedef struct UserID UserID;

/**
 * # Safety
 * `cert` must be non-null and from a `pgp_certificate_*` constructor.
 */
void pgp_certificate_free(struct Certificate *cert);

/**
 * # Safety
 * `key` must be non-null and from a `pgp_key_*` constructor.
 */
void pgp_key_free(struct Key *key);

/**
 * # Safety
 * `user_id` must be non-null and from a `pgp_user_id_*` constructor.
 */
void pgp_user_id_free(struct UserID *user_id);

/**
 * Parse an ASCII-armored PGP cert into `*cert`.
 *
 * # Safety
 * `armored` and `cert` must be non-null.
 */
int32_t pgp_certificate_from_armored(const char *armored, struct Certificate **cert);

/**
 * Generate a new certificate with the given user ID.
 *
 * # Safety
 * `user_id` and `new_cert` must be non-null.
 */
int32_t pgp_key_generate(const char *user_id, struct Certificate **new_cert);

#endif /* pgp_ffi_h */
