/*
 * This file is autogenerated by cbindgen. Do not modify this file manually.
 * To regenerate this file, run:
 * ```
 * cbindgen --config cbindgen.toml --crate monero-rust --output monero-rust.h
 * ```
 * from the project root.
 *
 * For more information, see the project documentation or contact the project maintainer.
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


/**
 * Decrypts a message and returns the plaintext.
 */
const char *decrypt_message(const char *cert_str, const char *ciphertext);

/**
 * Encrypts a message and returns the ciphertext.
 */
const char *encrypt_message(const char *cert_str, const char *message);

/**
 * Exports the generated key in ASCII-armored format.
 */
const char *export_ascii_key(const char *cert_str);

/**
 * Generates an encryption-capable key.
 */
const char *generate_key(void);
